export enum CANCELATION_TYPE {
    TOO_LATE = "TOO_LATE",
    UNREACHABLE = "UNREACHABLE",
    AFTER_7 = "AFTER_7",
    NO_GROUND = "NO_GROUND",
    NO_SUPPLY = "NO_SUPPLY",
    SLOW_SERVICE = "SLOW_SERVICE",
    VOLUNTARY = "VOLUNTARY",
}

export enum TRANSACTION_ACTION {
    REFUND = "REFUND",
    TOPUP = "TOPUP",
    PURCHASE = "PURCHASE",
}
